### ISSUE TITLE
Asynchronous race condition 

### ISSUE THREAD

**Issue by ashnur** [Raynos/main-loop#11]
AJAX can randomly complete during the render phase making the do not mutate in render a flaky bug

**Comment by kuraga** [comment]
What's the state?

**Comment by ashnur** [comment]
@kuraga what do you mean?

**Comment by kuraga** [comment]
@ashnur I mean
> I probably will have to wrap it in a try catch and set transition into a thrown state so that the next update() can rethrow a "broken main loop" exception instead of a "update in render phase" exception.

And it's good to have tests for "render during rendering"...
